name: money_controller
description: "A money controller app that tracks your remaining money to ensure fluent month goes on and establish a possibility of have some savings."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  shared_preferences: ^2.3.3
  fl_chart: ^0.69.2
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.4
  googleapis: ^15.0.0
  googleapis_auth: ^2.0.0
  google_sign_in: ^6.2.1
  path_provider: ^2.1.4
  http: ^1.2.2
  extension_google_sign_in_as_googleapis_auth: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
   - assets/logo.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/logo.png"
  min_sdk_android: 21
